FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend /app/frontend
ENV PYTHONPATH=/app/frontend
ENV STREAMLIT_SERVER_PORT=8501

CMD ["streamlit", "run", "/app/frontend/streamlit_app.py", "--server.address=0.0.0.0"]
